version: '3.8'

services:
  simulateur_producer:
      build:
        context: ../simulateur_producer
        dockerfile: Dockerfile
      image: glopcoder/simulateur_producer
      ports:
          - "3030:3030"
      environment:
          - SPRING.KAFKA.BOOTSTRAP-SERVERS=kafka:9092
      container_name: simulateur_producer
networks:
  glop_network:
    external:
      name: glop_network


