version: '3.8'

services:

  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=updateEpreuve, updateCompetition, updateCategorie
      - KRAFT_PARTITIONS_PER_TOPIC=3

  mas_evenements:
    build:
      context: ../mas_evenements
      dockerfile: Dockerfile
    image: glopcoder/mas_evenements
    ports:
        - "8080:8080"
    container_name: mas_evenements

  mas_participants:
    build:
      context: ../mas_participants
      dockerfile: Dockerfile
    image: glopcoder/mas_participants
    ports:
        - "8081:8081"
    container_name: mas_participants
    
  mas_localisation:
    build:
      context: ../mas_localisation
      dockerfile: Dockerfile
    image: glopcoder/mas_localisation
    ports:
        - "8082:8082"
    container_name: mas_localisation

  mas_gestionrdv:
    build:
      context: ../mas_gestionrdv
      dockerfile: Dockerfile
    image: glopcoder/mas_gestionrdv
    ports:
        - "8083:8083"
    container_name: mas_gestionrdv

  mas_notifications:
    build:
      context: ../mas_notifications
      dockerfile: Dockerfile
    image: glopcoder/mas_notifications
    ports:
        - "8084:8084"
    container_name: mas_notifications

  mas_authentification:
      build:
        context: ../mas_authentification
        dockerfile: Dockerfile
      image: glopcoder/mas_authentification
      ports:
          - "8085:8085"
      container_name: mas_authentification