version: '3.8'

services:
  mas_evenements:
    build:
      context: ../mas_evenements
      dockerfile: Dockerfile
    image: glopcoder/mas_evenements
    ports:
        - "8080:8080"
    container_name: mas_evenements
