version: '3.8'

services:
  mas_evenements:
    build:
      context: ../mas_evenements
      dockerfile: Dockerfile
    image: glopcoder/mas_evenements
    ports:
        - "8080:8080"
    container_name: mas_evenements
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
      SPRING_DATASOURCE_USERNAME: GLOP41
      SPRING_DATASOURCE_PASSWORD: novembre22

  mas_participants:
    build:
      context: ../mas_participants
      dockerfile: Dockerfile
    image: glopcoder/mas_participants
    ports:
        - "8081:8081"
    container_name: mas_participants
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
      SPRING_DATASOURCE_USERNAME: GLOP46
      SPRING_DATASOURCE_PASSWORD: novembre22
    
  mas_localisation:
    build:
      context: ../mas_localisation
      dockerfile: Dockerfile
    image: glopcoder/mas_localisation
    ports:
        - "8082:8082"
    container_name: mas_localisation

  mas_gestionrdv:
    build:
      context: ../mas_gestionrdv
      dockerfile: Dockerfile
    image: glopcoder/mas_gestionrdv
    ports:
        - "8083:8083"
    container_name: mas_gestionrdv

  mas_notifications:
    build:
      context: ../mas_notifications
      dockerfile: Dockerfile
    image: glopcoder/mas_notifications
    ports:
        - "8084:8084"
    container_name: mas_notifications