version: '3.8'

services:
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=updateEpreuve, 
                            updateCompetition, 
                            updateCategorie, 
                            updateAthlete, 
                            updateTeam, 
                            updateParticipate,
                            createEpreuve,
                            createCategorie,
                            createCompetition,
                            createAthlete,
                            createTeam,
                            createParticipate,
                            createLieu,
                            updateLieu,
                            createRdv,
                            updateRdv,
                            createAgenda,
                            updateAgenda
      - KRAFT_PARTITIONS_PER_TOPIC=3

  mas_evenements:
    build:
      context: ../mas_evenements
      dockerfile: Dockerfile
    image: glopcoder/mas_evenements
    ports:
        - "8080:8080"
    environment:
          - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
          - SPRING.DATASOURCE.USERNAME=GLOP41
          - SPRING.DATASOURCE.PASSWORD=novembre22
          - SPRING_PROFILES_ACTIVE=prod
    container_name: mas_evenements

  mas_participants:
    build:
      context: ../mas_participants
      dockerfile: Dockerfile
    image: glopcoder/mas_participants
    ports:
        - "8081:8081"
    environment:
          - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
          - SPRING.DATASOURCE.USERNAME=GLOP46
          - SPRING.DATASOURCE.PASSWORD=novembre22
          - SPRING_PROFILES_ACTIVE=prod
    container_name: mas_participants
    
  mas_localisation:
    build:
      context: ../mas_localisation
      dockerfile: Dockerfile
    image: glopcoder/mas_localisation
    ports:
        - "8082:8082"
    environment:
          - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
          - SPRING.DATASOURCE.USERNAME=GLOP42
          - SPRING.DATASOURCE.PASSWORD=novembre22
          - SPRING_PROFILES_ACTIVE=prod
    container_name: mas_localisation

  mas_gestionrdv:
    build:
      context: ../mas_gestionrdv
      dockerfile: Dockerfile
    image: glopcoder/mas_gestionrdv
    ports:
        - "8083:8083"
    environment:
          - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
          - SPRING.DATASOURCE.USERNAME=GLOP43
          - SPRING.DATASOURCE.PASSWORD=novembre22
          - SPRING_PROFILES_ACTIVE=prod
    container_name: mas_gestionrdv

  mas_authentification:
      build:
        context: ../mas_authentification
        dockerfile: Dockerfile
      image: glopcoder/mas_authentification
      ports:
          - "8085:8085"
      environment:
          - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
          - SPRING.DATASOURCE.USERNAME=GLOP44
          - SPRING.DATASOURCE.PASSWORD=novembre22
          - SPRING_PROFILES_ACTIVE=prod
      container_name: mas_authentification

  mas_gateway:
    build:
      context: ../mas_gateway
      dockerfile: Dockerfile
    image: glopcoder/mas_gateway
    ports:
        - "8086:8086"
    environment:
        - SPRING.KAFKA.BOOTSTRAP-SERVERS=kafka:9092
    container_name: mas_gateway

  simulateur_producer:
      build:
        context: ../simulateur_producer
        dockerfile: Dockerfile
      image: glopcoder/simulateur_producer
      ports:
          - "3030:3030"
      environment:
          - SPRING.KAFKA.BOOTSTRAP-SERVERS=kafka:9092
      container_name: simulateur_producer
#networks:
#  glop_network:
#    external:
#      name: glop_network

  #mas_notifications:
  #  build:
  #    context: ../mas_notifications
  #    dockerfile: Dockerfile
  #  image: glopcoder/mas_notifications
  #  ports:
  #      - "8084:8084"
  #  environment:
  #        - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
  #        - SPRING.DATASOURCE.USERNAME=GLOP45
  #        - SPRING.DATASOURCE.PASSWORD=novembre22
  #        - SPRING_PROFILES_ACTIVE=prod
  #  container_name: mas_notifications